### PR TITLE
Fix reactor status check

### PR DESCRIPTION
**Pull request by codeadict**
Added functionality to check the reactor status as specified in https://developers.evrythng.com/docs/reactor#section-read-the-reactor-script-status

### CODE REVIEW

**Comment by augustawind** [comment]
- [x] CR

**Comment by ramonPaulAlvarez** [comment]
CR+1 - I'll need to update my version an extra number now.

**Comment by rtrajano** [comment]
**CR+1** 👍

**Comment by LyleScott** [comment]
CR+1

**Pull request merged**
