### PR TITLE
Providing response objects from property deletions.

### PR DESCRIPTION
**Pull request by ramonPaulAlvarez**
- We'd like to check the responses from EVT and these weren't returning them.

### CODE REVIEW

**Review by codeadict — COMMENTED** [review]
I think there is an unneeded whitespace

**Comment by ramonPaulAlvarez** [comment]
The return statements with the call in them look right to me since the next argument begins where the first one started.  That's how all of my indentation is done in this context.  Perhaps GitHub is playing a trick on you.  Can you confirm?

**Review by LyleScott — APPROVED** [review]
nice catch!

**Comment by codeadict** [comment]
Yep Ramon, is fine. Had to use the side by side diff

**Pull request merged**
