### PR TITLE
fix for bug

### PR DESCRIPTION
**Pull request by rtrajano**
not sure how to test this yet.

### CODE REVIEW

**Review by LyleScott — APPROVED** [review]

**Comment by dudymas** [comment]
LGTM

**Review by dudymas — APPROVED** [review]
ship it

**Review by codeadict — APPROVED** [review]

**Review by augustawind — APPROVED** [review]
whoops, sorry my fault, copypasta on autopilot. thanks

**Comment by augustawind** [comment]
we really need unittests for this repo...

**Comment by dudymas** [comment]
merge merge merge

**Review by augustawind — APPROVED** [review]

**Pull request merged**
